[install]
exact = true
linker = "isolated"
linkWorkspacePackages = true
saveTextLockfile = true
minimumReleaseAge = 259200 # 3 days

[install.security]
scanner = "@socketsecurity/bun-security-scanner"
